apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-ssm
  annotations:
    arn:aws:iam::710990938946:role/eks-ssm-ps-prod-role

---
apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  serviceAccountName: oidc-ssm
  comtainers:
    - name: sample-pod
      image:
      imagePullPolicy: Always